version: '3.8'

services:
  app:
    build:
      context: ./app
    ports:
      - "5111:5111"
    depends_on:
      - db

  db:
    image: postgres:15
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: password
      POSTGRES_DB: microservice_db
    volumes:
      - db_data:/var/lib/postgresql/data

volumes:
  db_data:
